/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testingRando(){
        Library sut = new Library();
        int randomNumberResult = sut.rando();
        assertTrue(randomNumberResult < 7);
        assertTrue(randomNumberResult > 0);

    }
    @Test void testingContainsDuplicate(){
        Library sut = new Library();
        int[] arr = new int[]{1,2,3,3,5,6};
        boolean duplicateChecker = sut.containsDuplicates(arr);
        assertTrue(duplicateChecker);

    }
    @Test void noDuplicates(){
        Library sut = new Library();
        int[] arr = new int[]{1,2,3,4,5,6};
        boolean duplicateChecker = sut.containsDuplicates(arr);
        assertFalse(duplicateChecker);
    }
    @Test void averageInTheArrayChecker(){
        Library sut = new Library();
        int[] arr = new int[]{2,4,6};
        int calculatingAverages = sut.calculatingAverages(arr);
        assertEquals(4, sut.calculatingAverages(arr));

    }
    @Test public void arrayOfArrays(){
        Library sut = new Library();
        int[][] randomNumbers = {
                {54, 55, 56, 67, 90, 10, 25},
                {91, 99, 300, 400, 20, 1, 19},
                {100, 200, 300, 400, 500, 600, 700},
                {1, 2, 3, 4, 5, 6, 7}
        };
        assertEquals(randomNumbers[3], sut.arrayOfArrays(randomNumbers));
        System.out.println(randomNumbers[3]);
    }
    @Test public void anotherArrayOfArrays() {
        Library sut = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        // figure out how to test this));

    };
    @Test public void winner() {
        List<String> votes = new ArrayList<>();
        Library sut = new Library();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        assertEquals( "Bush received the most votes!",
                sut.tally(votes));
        System.out.println(sut.tally(votes));
    }
}
